# Operations Base Configuration for Data & Monitoring Agents
# Provides database and monitoring access for operational agents
# Used by: analytics-reporter, infrastructure-maintainer, support-responder

# Operations Tools with Data Access
operations_tools:
  # Essential File Operations
  - Read
  - Write
  - Edit
  - MultiEdit
  - LS
  
  # Command & Search Operations
  - Bash
  - Grep
  - Glob
  
  # Web Operations (for operational research)
  - WebSearch
  - WebFetch
  
  # Operations-Focused MCP Operations
  - mcp__git__                    # Version control (essential)
  - mcp__supabase__              # Database operations and analytics
  - mcp__sentry__                # Error monitoring and issue tracking
  - mcp__sequential-thinking__    # Operational analysis and troubleshooting
  - mcp__context7__              # Technical documentation
  # NO playwright (operations don't need browser), NO serena (not code-focused)

# Configuration Files All Operations Agents Should Reference
universal_config_files:
  - path: "/home/nathan/.claude/CONTEXT.md"
    description: "Environment setup, project structure, development workflow"
    words: 618
  - path: "/home/nathan/.claude/PRINCIPLES.md" 
    description: "Development philosophy, SOLID principles, senior mindset"
    words: 757
  - path: "/home/nathan/.claude/RULES.md"
    description: "Operational safety, validation sequences, quality gates"
    words: 505
  - path: "/home/nathan/.claude/MCP.md"
    description: "Tool selection, server coordination, performance optimization"
    words: 2918
  - path: "/home/nathan/.claude/AGENTS.md"
    description: "Agent selection guide, specializations, orchestration patterns"
    words: 1575

# OPERATIONS SPECIALIZATION RATIONALE:
# - supabase MCP: Essential for database queries, analytics, user data operations
# - sentry MCP: Critical for error monitoring, performance tracking, issue management
# - git MCP: Required for deployment tracking and configuration management
# - sequential-thinking: Necessary for complex operational troubleshooting
# - context7: Essential for operational documentation and runbook access
# - NO code analysis: Operations agents focus on running systems, not code structure
# - NO browser automation: Operations work with APIs and databases, not UI

# SECURITY CONSIDERATIONS:
# Database and monitoring access restricted to operations agents only
# Prevents unauthorized data access from general-purpose agents
# Operations agents should handle sensitive production data responsibly

# Total Context Cost: 6,373 words (~13,153 tokens)
# Updated: 2025-08-19 with operations-specific MCP restrictions

# Usage Instructions:
# 1. Operations agents reference "@operations-base-config.yml"
# 2. Inherits operations tools including database and monitoring access
# 3. Provides data analytics and error tracking capabilities
# 4. Maintains security by restricting access to authorized operations agents

# Example Operations Agent Structure:
# ---
# name: system-monitor
# description: |
#   Monitors system health and analyzes operational metrics.
#   @operations-base-config.yml
# color: red
# ---